#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Set Powerlevel9k mode before Prezto is loaded.
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_DIR_SHOW_WRITABLE=true

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Fix emacs tramp.
[ $TERM = 'dumb' ] && unsetopt zle

# https://github.com/junegunn/fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Source local config.
[ -f $HOME/.zshrc.local ] && source $HOME/.zshrc.local
