#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
ZSH_HIGHLIGHT_PATTERNS+=('rm -rf *' 'fg=15,bg=red')

# Fix emacs tramp.
[ $TERM = 'dumb' ] && unsetopt zle

# https://github.com/junegunn/fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Source local config.
[ -f $HOME/.zshrc.local ] && source $HOME/.zshrc.local
